/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookbuddy;

import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;

/**
 * Author: Rosie and Anita
 * Panel that displays book information
 * Date: June 6, 2024
 */
public class BookPanel extends javax.swing.JPanel {

    private Book book;
    private HashMap bookInfo;
    private File f = new File("savedRatings.txt");

    //-----------------------------------------------------------------------------
    //Constructor
    /**
     * Creates new form BookPanel
     */
    public BookPanel() {
        initComponents();
    }
    
    //-----------------------------------------------------------------------------
    //Methods

    /**
     * Rosie
     * load book information onto book panel
     * @param g graphics component
     */

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        //only need to update the jLabels once 
        if (SearchPanel.searchDone) {
            bookInfo = SearchPanel.bookInfo;
            System.out.println("ello");
            book = new Book(bookInfo);
            displayInformation(book);
            displayRatings();
            SearchPanel.searchDone = false;
        }
        //load image
        try {
            BufferedImage img = ImageIO.read(new File("adminIcon.png"));
            adminButton.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            System.out.println("TRY AAIN");
        }
        
        g.drawImage(book.getImage(), 53, 60, 181, 266, null);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorLabel = new javax.swing.JLabel();
        ratingsLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        addRatingButton = new javax.swing.JButton();
        titleLabel5 = new javax.swing.JLabel();
        bookTitle = new javax.swing.JLabel();
        bookAuthor = new javax.swing.JLabel();
        bookIsbn = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookDesc = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        ratingTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 57, 85));
        setPreferredSize(new java.awt.Dimension(900, 600));

        authorLabel.setBackground(new java.awt.Color(153, 57, 85));
        authorLabel.setFont(new java.awt.Font("Georgia", 0, 21)); // NOI18N
        authorLabel.setForeground(new java.awt.Color(251, 246, 229));
        authorLabel.setText("AUTHOR:");

        ratingsLabel.setBackground(new java.awt.Color(153, 57, 85));
        ratingsLabel.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        ratingsLabel.setForeground(new java.awt.Color(251, 246, 229));
        ratingsLabel.setText("RATINGS");

        isbnLabel.setBackground(new java.awt.Color(153, 57, 85));
        isbnLabel.setFont(new java.awt.Font("Georgia", 0, 21)); // NOI18N
        isbnLabel.setForeground(new java.awt.Color(251, 246, 229));
        isbnLabel.setText("ISBN#:");

        descLabel.setBackground(new java.awt.Color(153, 57, 85));
        descLabel.setFont(new java.awt.Font("Georgia", 0, 21)); // NOI18N
        descLabel.setForeground(new java.awt.Color(251, 246, 229));
        descLabel.setText("DESCRIPTION:");

        addRatingButton.setBackground(new java.awt.Color(240, 150, 197));
        addRatingButton.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        addRatingButton.setForeground(new java.awt.Color(251, 246, 229));
        addRatingButton.setText("ADD");
        addRatingButton.setBorder(null);
        addRatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRatingButtonActionPerformed(evt);
            }
        });

        titleLabel5.setBackground(new java.awt.Color(153, 57, 85));
        titleLabel5.setFont(new java.awt.Font("Georgia", 0, 21)); // NOI18N
        titleLabel5.setForeground(new java.awt.Color(251, 246, 229));
        titleLabel5.setText("TITLE:");

        bookTitle.setBackground(new java.awt.Color(153, 57, 85));
        bookTitle.setFont(new java.awt.Font("Georgia", 0, 21)); // NOI18N
        bookTitle.setForeground(new java.awt.Color(251, 246, 229));
        bookTitle.setText("Lorem ipsum ");

        bookAuthor.setBackground(new java.awt.Color(153, 57, 85));
        bookAuthor.setFont(new java.awt.Font("Georgia", 0, 21)); // NOI18N
        bookAuthor.setForeground(new java.awt.Color(251, 246, 229));
        bookAuthor.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit,");

        bookIsbn.setBackground(new java.awt.Color(153, 57, 85));
        bookIsbn.setFont(new java.awt.Font("Georgia", 0, 21)); // NOI18N
        bookIsbn.setForeground(new java.awt.Color(251, 246, 229));
        bookIsbn.setText("9781423168232/1234758392");

        backButton.setBackground(new java.awt.Color(12, 38, 89));
        backButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(251, 246, 229));
        backButton.setText("<");
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        adminButton.setBackground(new java.awt.Color(153, 57, 85));
        adminButton.setBorder(null);
        adminButton.setBorderPainted(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        bookDesc.setEditable(false);
        bookDesc.setBackground(new java.awt.Color(153, 57, 85));
        bookDesc.setColumns(20);
        bookDesc.setFont(new java.awt.Font("Georgia", 0, 21)); // NOI18N
        bookDesc.setForeground(new java.awt.Color(251, 246, 229));
        bookDesc.setLineWrap(true);
        bookDesc.setRows(5);
        bookDesc.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit,");
        bookDesc.setWrapStyleWord(true);
        bookDesc.setBorder(null);
        bookDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bookDesc.setFocusable(false);
        jScrollPane2.setViewportView(bookDesc);

        ratingTextArea.setBackground(new java.awt.Color(153, 57, 85));
        ratingTextArea.setColumns(20);
        ratingTextArea.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        ratingTextArea.setForeground(new java.awt.Color(246, 250, 221));
        ratingTextArea.setLineWrap(true);
        ratingTextArea.setRows(5);
        jScrollPane1.setViewportView(ratingTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ratingsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isbnLabel)
                            .addComponent(descLabel))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(addRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bookAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(bookIsbn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(13, 13, 13)))
                        .addGap(0, 1, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addRatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRatingButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        CardLayout c = (CardLayout) topFrame.bgPanel.getLayout();
        c.show(topFrame.bgPanel, "card4");
    }//GEN-LAST:event_addRatingButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        System.out.println(this + ": " + topFrame);
        CardLayout c = (CardLayout) topFrame.bgPanel.getLayout();
        c.show(topFrame.bgPanel, "card3");
    }//GEN-LAST:event_backButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        CardLayout c = (CardLayout) topFrame.bgPanel.getLayout();
        c.show(topFrame.bgPanel, "card5");
    }//GEN-LAST:event_adminButtonActionPerformed

    /**
     * Rosie
     * load information into JLabels
     * @param book object
     */
    private void displayInformation(Book book) {
        bookTitle.setText(book.getTitle());
        bookAuthor.setText(book.getAuthor());
        bookIsbn.setText(book.getIsbn10() + "/" + book.getIsbn13());
        bookDesc.setText(book.getDescription());
    }

    //anita
    private void displayRatings() {
        book.loadRatings();
        
        ArrayList<Rating> ratings = book.getRatings();
        for(Rating rating : ratings) {
            String ratingText = " A student " + rating.getStudentNum() + " in grade " + rating.getStudentGrade() + 
                                " gives this book " + rating.getStarRating() + " stars and says: " + rating.getComments();
            ratingTextArea.append(ratingText);
            ratingTextArea.revalidate();
            ratingTextArea.repaint();
            
        } 
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRatingButton;
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookAuthor;
    private javax.swing.JTextArea bookDesc;
    private javax.swing.JLabel bookIsbn;
    private javax.swing.JLabel bookTitle;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ratingTextArea;
    private javax.swing.JLabel ratingsLabel;
    private javax.swing.JLabel titleLabel5;
    // End of variables declaration//GEN-END:variables
}
