/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookbuddy;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.SwingUtilities;

/**
 *
 * @author owner1
 */
public class NewRatingPanel extends javax.swing.JPanel {

    Book bookTitle;
    int selectedRating = 0;
    int selectedGrade = 0;
    Color lightPink1 = new Color(240, 150, 197);
    Color cream1 = new Color(246, 250, 221);
    
    /**
     * Creates new form NewRatingPanel
     */
    public NewRatingPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        bookTitle = new Book(SearchPanel.bookInfo);
        System.out.println("TITLE: " + bookTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        oneStar = new javax.swing.JButton();
        twoStar = new javax.swing.JButton();
        threeStar = new javax.swing.JButton();
        fourStar = new javax.swing.JButton();
        fiveStar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comments = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        grade9 = new javax.swing.JButton();
        grade10 = new javax.swing.JButton();
        grade11 = new javax.swing.JButton();
        grade12 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saveRatingButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 57, 85));
        setForeground(new java.awt.Color(153, 57, 85));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 250, 221));
        jLabel1.setText("New Rating");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 250, 221));
        jLabel2.setText("Scan Student ID");

        studentID.setBackground(new java.awt.Color(246, 250, 221));
        studentID.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        studentID.setForeground(new java.awt.Color(153, 57, 85));

        oneStar.setBackground(new java.awt.Color(153, 57, 85));
        oneStar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        oneStar.setForeground(new java.awt.Color(246, 250, 221));
        oneStar.setText("⭑");
        oneStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneStarActionPerformed(evt);
            }
        });

        twoStar.setBackground(new java.awt.Color(153, 57, 85));
        twoStar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        twoStar.setForeground(new java.awt.Color(246, 250, 221));
        twoStar.setText("⭑");
        twoStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoStarActionPerformed(evt);
            }
        });

        threeStar.setBackground(new java.awt.Color(153, 57, 85));
        threeStar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        threeStar.setForeground(new java.awt.Color(246, 250, 221));
        threeStar.setText("⭑");
        threeStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeStarActionPerformed(evt);
            }
        });

        fourStar.setBackground(new java.awt.Color(153, 57, 85));
        fourStar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fourStar.setForeground(new java.awt.Color(246, 250, 221));
        fourStar.setText("⭑");
        fourStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourStarActionPerformed(evt);
            }
        });

        fiveStar.setBackground(new java.awt.Color(153, 57, 85));
        fiveStar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fiveStar.setForeground(new java.awt.Color(246, 250, 221));
        fiveStar.setText("⭑");
        fiveStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveStarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(246, 250, 221));
        jLabel3.setText("Select Star Rating");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 250, 221));
        jLabel4.setText("Add Comments");

        comments.setBackground(new java.awt.Color(246, 250, 221));
        comments.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        comments.setForeground(new java.awt.Color(153, 57, 85));
        comments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 250, 221));
        jLabel5.setText("Select Your Grade");

        grade9.setBackground(new java.awt.Color(246, 250, 221));
        grade9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        grade9.setForeground(new java.awt.Color(153, 57, 85));
        grade9.setText("9");
        grade9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade9ActionPerformed(evt);
            }
        });

        grade10.setBackground(new java.awt.Color(246, 250, 221));
        grade10.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        grade10.setForeground(new java.awt.Color(153, 57, 85));
        grade10.setText("10");
        grade10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade10ActionPerformed(evt);
            }
        });

        grade11.setBackground(new java.awt.Color(246, 250, 221));
        grade11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        grade11.setForeground(new java.awt.Color(153, 57, 85));
        grade11.setText("11");
        grade11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade11ActionPerformed(evt);
            }
        });

        grade12.setBackground(new java.awt.Color(246, 250, 221));
        grade12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        grade12.setForeground(new java.awt.Color(153, 57, 85));
        grade12.setText("12");
        grade12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade12ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 250, 221));
        jLabel6.setText("Reminder");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 250, 221));
        jLabel7.setText("BookBuddy is a school");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 250, 221));
        jLabel8.setText("affiliated library rating system.");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 250, 221));
        jLabel9.setText("Please ensure your ratings ");

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(246, 250, 221));
        jLabel10.setText("are school appropriate.");

        saveRatingButton.setBackground(new java.awt.Color(246, 250, 221));
        saveRatingButton.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        saveRatingButton.setForeground(new java.awt.Color(153, 57, 85));
        saveRatingButton.setText("Save");
        saveRatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRatingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grade9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(grade10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grade11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(grade12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comments, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(385, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oneStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(twoStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(threeStar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fourStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fiveStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(saveRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(51, 51, 51))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oneStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(twoStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(threeStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fourStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiveStar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(comments, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grade9)
                            .addComponent(grade10)
                            .addComponent(grade11)
                            .addComponent(grade12))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oneStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneStarActionPerformed
        selectedRating = 1;
        oneStar.setBackground(lightPink1);
    }//GEN-LAST:event_oneStarActionPerformed

    private void commentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentsActionPerformed

    private void grade11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade11ActionPerformed
        selectedGrade = 11;
        grade11.setBackground(lightPink1);
        grade9.setBackground(cream1);
        grade10.setBackground(cream1);
        grade12.setBackground(cream1);
    }//GEN-LAST:event_grade11ActionPerformed

    private void saveRatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRatingButtonActionPerformed
        int num = Integer.parseInt(studentID.getText());
        String comment = comments.getText();
        String title = bookTitle.getTitle();
        Rating r = new Rating(num, selectedGrade, selectedRating, comment, title);
        System.out.println("hi");
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        CardLayout c = (CardLayout) topFrame.bgPanel.getLayout();
        c.show(topFrame.bgPanel, "card2");
    }//GEN-LAST:event_saveRatingButtonActionPerformed

    private void twoStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoStarActionPerformed
        selectedRating = 2;
        twoStar.setBackground(lightPink1);
    }//GEN-LAST:event_twoStarActionPerformed

    private void threeStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeStarActionPerformed
        selectedRating = 3;
        threeStar.setBackground(lightPink1);
    }//GEN-LAST:event_threeStarActionPerformed

    private void fourStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourStarActionPerformed
        selectedRating = 4;
        fourStar.setBackground(lightPink1);
    }//GEN-LAST:event_fourStarActionPerformed

    private void fiveStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveStarActionPerformed
        selectedRating = 5;
        fiveStar.setBackground(lightPink1);
    }//GEN-LAST:event_fiveStarActionPerformed

    private void grade9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade9ActionPerformed
        selectedGrade = 9;
        grade9.setBackground(lightPink1);
        grade10.setBackground(cream1);
        grade11.setBackground(cream1);
        grade12.setBackground(cream1);
    }//GEN-LAST:event_grade9ActionPerformed

    private void grade10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade10ActionPerformed
        selectedGrade = 10;
        grade10.setBackground(lightPink1);
        grade11.setBackground(cream1);
        grade12.setBackground(cream1);
        grade9.setBackground(cream1);
    }//GEN-LAST:event_grade10ActionPerformed

    private void grade12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade12ActionPerformed
        selectedGrade = 12;
        grade12.setBackground(lightPink1);
        grade11.setBackground(cream1);
        grade10.setBackground(cream1);
        grade9.setBackground(cream1);
    }//GEN-LAST:event_grade12ActionPerformed

                                          
/*
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
    }//GEN-LAST:event_jButton5ActionPerformed
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comments;
    private javax.swing.JButton fiveStar;
    private javax.swing.JButton fourStar;
    private javax.swing.JButton grade10;
    private javax.swing.JButton grade11;
    private javax.swing.JButton grade12;
    private javax.swing.JButton grade9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton oneStar;
    private javax.swing.JButton saveRatingButton;
    private javax.swing.JTextField studentID;
    private javax.swing.JButton threeStar;
    private javax.swing.JButton twoStar;
    // End of variables declaration//GEN-END:variables
}
