/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookbuddy;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 * Author: Rosie
 * Admin login panel
 * Date: June 6, 2024
 */
public class SecretCodePanel extends javax.swing.JPanel {

    //secret code final variable
    final static String CODE = "CSROCKS123";

    /**
     * Creates new form SecretCodePanel
     */
    public SecretCodePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingsLabel = new javax.swing.JLabel();
        codeTextField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 57, 85));

        ratingsLabel.setBackground(new java.awt.Color(153, 57, 85));
        ratingsLabel.setFont(new java.awt.Font("Georgia", 0, 58)); // NOI18N
        ratingsLabel.setForeground(new java.awt.Color(251, 246, 229));
        ratingsLabel.setText("ADMIN LOGIN");

        codeTextField.setBackground(new java.awt.Color(246, 250, 221));
        codeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        codeTextField.setForeground(new java.awt.Color(153, 57, 85));
        codeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTextFieldActionPerformed(evt);
            }
        });

        messageLabel.setBackground(new java.awt.Color(153, 57, 85));
        messageLabel.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(251, 246, 229));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("ENTER ADMIN CODE");
        messageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        enterButton.setBackground(new java.awt.Color(240, 150, 197));
        enterButton.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        enterButton.setForeground(new java.awt.Color(251, 246, 229));
        enterButton.setText("ENTER");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(12, 38, 89));
        backButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(251, 246, 229));
        backButton.setText("<");
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(ratingsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(enterButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ratingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTextFieldActionPerformed

    //Rosie
    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        //check if entered code is correct
        if (CODE.equals(codeTextField.getText())) {
            MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
            CardLayout c = (CardLayout) topFrame.bgPanel.getLayout();
            c.show(topFrame.bgPanel, "card6");
        } else {
            messageLabel.setText("INVALID CODE");
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    //Rosie
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainFrame topFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        CardLayout c = (CardLayout) topFrame.bgPanel.getLayout();
        c.show(topFrame.bgPanel, "card2");
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel ratingsLabel;
    // End of variables declaration//GEN-END:variables
}
